spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chaeheesung33@gmail.com
    password: ${password}
    properties:
      mail :
        smtp:
          auth: true
          starttls:
            enable: true
